config/routes.rb
Humongous::Application.routes.draw do

  root :to => 'inspections#index'

  resources :inspections

end

app/models/address.rb
class Address
  include Mongoid::Document

  field :street, :type => String
  field :city, :type => String
  field :state, :type => String
  field :zip, :type => String

  validates :street, :presence => true
  validates :city, :presence => true
  validates :state, :presence => true
  validates :zip, :presence => true

  embedded_in :inspection, :inverse_of => :address  
end

app/models/inspection.rb
class Inspection
  include Mongoid::Document

  field :name, :type => String
  field :notes, :type => String
  field :started_at, :type => Time
  field :finished_at, :type => Time
  field :total_observables, :type => Integer

  attr_protected :total_observables

  validates :name, :presence => true

  embeds_one :address
  embeds_many :observables

  index :finished_at

  before_save :calculate_total_observables

  private
  
  def calculate_total_observables
    self.total_observables = observables.collect { |o| count_observables(o) }.sum
  end

  def count_observables(observable)
    observable.observables.collect { |o| count_observables(o) }.sum + 1
  end
end

app/models/observable.rb
class Observable
  include Mongoid::Document

  CONDITIONS = ['new', 'like-new', 'used', 'damaged'].freeze

  field :name, :type => String
  field :condition, :type => String
  field :notes, :type => String

  validates :name, :presence => true
  validates :condition, :inclusion => {:in => CONDITIONS}

  embedded_in :inspection, :inverse_of => :observables
  embeds_many :observables
  embedded_in :observable, :inverse_of => :observables
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/inspections_controller.rb
class InspectionsController < ApplicationController
  def index
    @inspections = Inspection.desc(:finished_at).paginate :page => params[:page], :per_page => 50
    #render :text => "index page: #{@inspections.collect { |i| i.total_observables }.sum} total observables for #{@inspections.length} inspections"
  end

  def show
    @inspection = Inspection.find(params[:id])
    #render :text => "show page for #{@inspection.name}"
  end

  def new
    @inspection = Inspection.new
  end

  def edit
    @inspection = Inspection.find(params[:id])
  end

  def create
    @inspection = Inspection.new(params[:inspection])

    if @inspection.save
      redirect_to(@inspection, :notice => 'Inspection was successfully created.')
    else
      render :action => "new"
    end
  end

  def update
    @inspection = Inspection.find(params[:id])

    if @inspection.update_attributes(params[:inspection])
      redirect_to(@inspection, :notice => 'Inspection was successfully updated.')
    else
      render :action => "edit"
    end
  end

  def destroy
    @inspection = Inspection.find(params[:id])
    @inspection.destroy

    redirect_to(inspections_url, :notice => 'Inspection was successfully deleted.')
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/inspections_helper.rb
module InspectionsHelper
end

app/views/inspections/_form.html.erb
<%= form_for(@inspection) do |f| %>
  <% if @inspection.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@inspection.errors.count, "error") %> prohibited this inspection from being saved:</h2>

      <ul>
      <% @inspection.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :notes %><br />
    <%= f.text_area :notes %>
  </div>
  <div class="field">
    <%= f.label :started_at %><br />
    <%= f.datetime_select :started_at %>
  </div>
  <div class="field">
    <%= f.label :finished_at %><br />
    <%= f.datetime_select :finished_at %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/inspections/_observable.html.erb
<b><%= observable.name %></b>
<% if observable.condition.present? %>
   [<%= observable.condition.capitalize %>]
<% end %>
<% if observable.notes.present? %>
  <br/><%= observable.notes %>
<% end %>
<%= render :partial => 'observables', :locals => {:observables => observable.observables} %>

app/views/inspections/_observables.html.erb
<% if observables.present? %>
  <ul>
    <% observables.each do |observable| %>
      <li>
        <%= render :partial => 'observable', :locals => {:observable => observable} %>
      </li>
    <% end %>
  </ul>
<% end %>

app/views/inspections/edit.html.erb
<h1>Editing inspection</h1>

<%= render 'form' %>

<%= link_to 'Show', @inspection %> |
<%= link_to 'Back', inspections_path %>

app/views/inspections/index.html.erb
<h1>Inspections</h1>

<table>
  <tr>
    <th>Name</th>
    <th># Observables</th>
    <!--<th>Notes</th>-->
    <!--<th>Started at</th>-->
    <th>Finished at</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @inspections.each do |inspection| %>
  <tr>
    <td><%= inspection.name %></td>
    <td><%= inspection.total_observables %></td>
    <!--<td><%= truncate(inspection.notes, :length => 30) %></td>-->
    <!--<td><%= inspection.started_at %></td>-->
    <td><%= inspection.finished_at %></td>
    <td><%= link_to 'Show', inspection %></td>
    <td><%= link_to 'Edit', edit_inspection_path(inspection) %></td>
    <td><%= link_to 'Destroy', inspection, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>
<br />
<%= will_paginate @inspections %>
<br />

<%= link_to 'New Inspection', new_inspection_path %>

app/views/inspections/new.html.erb
<h1>New inspection</h1>

<%= render 'form' %>

<%= link_to 'Back', inspections_path %>

app/views/inspections/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @inspection.name %>
</p>

<p>
  <b>Notes:</b>
  <%= @inspection.notes %>
</p>

<p>
  <b>Started at:</b>
  <%= @inspection.started_at %>
</p>

<p>
  <b>Finished at:</b>
  <%= @inspection.finished_at %>
</p>

<% if @inspection.observables.present? %>
  <%= render :partial => 'observables', :locals => {:observables => @inspection.observables} %>
<% else %>
  <p>No observables for this inspection.</p>
<% end %>

<%= link_to 'Edit', edit_inspection_path(@inspection) %> |
<%= link_to 'Back', inspections_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Humongous</title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag 'jquery-1.4.2', 'rails', 'application' %>
  <%= csrf_meta_tag %>
</head>
<body>

<%= yield %>

</body>
</html>